### ISSUE TITLE
matrixStats error in fit_devil

### ISSUE THREAD

**Issue by giorgiagandolfi** [caravagnalab/devil#1]
I am trying to run `fit_devil` function and I got this error:

```
> fit <- fit_devil(counts, design_matrix, overdispersion = T, size_factors = T, verbose = T, parallel = T)
Compute size factors
Error: [matrixStats (>= 1.2.0)] useNames = NA is defunct. Instead, specify either useNames = TRUE or useNames = FALSE. See also ?matrixStats::matrixStats.options
```

**Comment by caravagn** [comment]
Any issue that gets opened should have minimum code to reproduce the error, otherwise it's very hard to fix it.

Please provide one.

**Comment by jovoni** [comment]
As today, the solution is to either downgrade the `matrixStats` package using

```
remotes::install_version("matrixStats", version="1.1.0")
```

or by updating Bioconductor to the latest version.
